from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('overview/', views.overview, name='overview'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/staking-earn/', views.staking_earn, name='staking_earn'),
    path('dashboard/convert-asset/', views.convert_asset, name='convert_asset'),
    path('dashboard/news/', views.news_dashboard, name='news_dashboard'),
    path('dashboard/margin/', views.margin_dashboard, name='margin_dashboard'),
    path('dashboard/futures/', views.futures_dashboard, name='futures_dashboard'),
    path('wallet/fiat-spot/', views.fiat_spot, name='fiat_spot'),
    path('account/verification/', views.verification, name='verification'),
    path('account/security/', views.security, name='security'),
    path('dashboard/trade-history/', views.trade_history, name='trade_history'),
    path('api/market/ohlcv/', views.market_ohlcv, name='market_ohlcv'),
    path('api/market/price/', views.market_price, name='market_price'),
    path('api/market/depth/', views.market_depth, name='market_depth'),
    path('api/market/trades/', views.market_trades, name='market_trades'),
    path('api/market/tickers/', views.market_tickers, name='market_tickers'),
    path('api/market/top-assets/', views.top_assets, name='top_assets'),
    path('api/market/news/', views.market_news, name='market_news'),
    path('api/account/settings/profile/', views.save_settings_profile, name='save_settings_profile'),
    path('api/account/settings/notifications/', views.save_settings_notifications, name='save_settings_notifications'),
    path('api/account/settings/appearance/', views.save_settings_appearance, name='save_settings_appearance'),
    path('login/', views.LoginAccountView.as_view(), name='login'),
    path('account/login/', views.LoginAccountView.as_view(), name='login_account'),
    path('wallet/deposit/', views.DepositView.as_view(), name='deposit'),
    path('wallet/payment/', views.PaymentView.as_view(), name='payment'),
    path('wallet/payment/complete/', views.PaymentCompleteView.as_view(), name='payment_complete'),
    path('signup/', views.SignupEmailView.as_view(), name='signup_start'),
    path('signup/password/', views.SignupPasswordView.as_view(), name='signup_password'),
    path('signup/verify-otp/', views.SignupVerifyOtpView.as_view(), name='signup_verify_otp'),
    path('signup/resend-otp/', views.SignupResendOtpView.as_view(), name='signup_resend_otp'),
    path('welcome/', views.WelcomeView.as_view(), name='welcome'),
]
